AWSTemplateFormatVersion: "2010-09-09"
Description: "Create S3 bucket"

Parameters:
  BucketName:
    Type: String
    Description: "Name of bucket"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref "BucketName"
      MetricsConfigurations:
        - Id: "EntireBucket" # "EntireBucket" is the default ID used by the AWS Console when enabling bucket-level metrics.
      WebsiteConfiguration:
        IndexDocument: "index.html"

Outputs:
  BucketName:
    Value: !Ref "S3Bucket"
    Description: "Name of bucket"
  BucketURL:
    Value: !Join ["", ["https://", !GetAtt [S3Bucket, DomainName]]]
    Description: "URL of bucket"
